---
- name: Ansible deploy wordpress with docker
  hosts: localhost
  gather_facts: no

  vars_files:
    - env.yml
    - pass.yml

  tasks:

    - include_tasks: new_wp_version.yml
      when: initialize_wp

    - include_tasks: build_docker_containers.yml

