---
- name: Ansible deploy wordpress with docker
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars/env.yml
    - vars/pass.yml

  tasks:

    - include_tasks: tasks/download_latest_wordpress.yml
      when: initialize_wp

    - include_tasks: tasks/build_docker_containers.yml

