name: Deploy to Amazon EC2 

on:
  push:
    branches: 
      - master

env:
  EC2_DOMAIN_NAME : "ec2-18-196-55-0.eu-central-1.compute.amazonaws.com"
  AWS_REGION_NAME : "eu-central-1b"
  

jobs:
  deplyment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: git clone our repo
      uses: actions/checkout@v1
      
    - name: SSH KEY 
      run: echo "${{ EC2_KEY }}" > ec2.pem
      
    - name: Copy repo to ec2
      run: scp -i ec2.pem ubuntu@$"{{ EC2_DOMAIN_NAME }}":~/
      
      
      
      
      
      
      
